# Generated by Django 4.2.11 on 2024-03-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0002_alter_url_clicks_alter_url_customized_link_and_more")
    ]

    operations = [
        migrations.AlterField(
            model_name="url", name="clicks", field=models.IntegerField(default=0)
        )
    ]
