# Generated by Django 4.2.11 on 2024-03-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("shortener", "0003_alter_url_clicks")]

    operations = [
        migrations.AlterField(
            model_name="url",
            name="customized_link",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="url",
            name="expiry_date",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
